import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from '@/providers/react-query/provider';
import AppThemeProvider from "@/providers/theme/provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppThemeProvider>
          <QueryProvider>
            {children}
            
          </QueryProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
